#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC68B494DF56ACC7E (info@zeek.org)
#
%define keepstatic 1
Name     : zeek
Version  : 5.0.2
Release  : 13
URL      : https://github.com/zeek/zeek/releases/download/v5.0.2/zeek-5.0.2.tar.gz
Source0  : https://github.com/zeek/zeek/releases/download/v5.0.2/zeek-5.0.2.tar.gz
Source1  : https://github.com/zeek/zeek/releases/download/v5.0.2/zeek-5.0.2.tar.gz.asc
Summary  : A fast JSON parser/generator for C++ with both SAX/DOM style API
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause BSL-1.0 CC-BY-4.0 ISC LGPL-3.0 MIT NCSA
Requires: pypi(pysubnettree)
BuildRequires : bison
BuildRequires : bison-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-meson
BuildRequires : curl-dev
BuildRequires : doxygen
BuildRequires : eigen-data
BuildRequires : flex
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : googletest-dev
BuildRequires : libpcap-dev
BuildRequires : opencl-headers-dev
BuildRequires : openmpi-dev
BuildRequires : openssl-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(openssl)
BuildRequires : protobuf-dev
BuildRequires : pypi(absl_py)
BuildRequires : pypi(gitpython)
BuildRequires : pypi(numpy)
BuildRequires : pypi(pandas)
BuildRequires : pypi(pybind11)
BuildRequires : pypi(pysubnettree)
BuildRequires : pypi(scipy)
BuildRequires : pypi(semantic_version)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(sphinx)
BuildRequires : pypi(sphinx_rtd_theme)
BuildRequires : pypi(wheel)
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : qt6base-dev
BuildRequires : swig
BuildRequires : zlib-dev
Patch1: 0001-Update-doctest-to-2.4.6.patch

%description
=================================
The Zeek Network Security Monitor
=================================

%prep
%setup -q -n zeek-5.0.2
cd %{_builddir}/zeek-5.0.2
%patch1 -p1

%build
## build_prepend content
# Use system-provided pysubnettree package
rm -v ./auxil/zeekctl/auxil/pysubnettree/CMakeLists.txt
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1666639564
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
%cmake .. -DCMAKE_INSTALL_PREFIX=/usr \
-DZEEK_ROOT_DIR=/usr \
-DZEEK_ETC_INSTALL_DIR=/etc \
-DINSTALL_ZEEKCTL=true \
-DZEEK_LOCAL_STATE_DIR=/var \
-DZEEK_SPOOL_DIR=/var/spool/zeek \
-DZEEK_LOG_DIR=/var/log/nsm/zeek \
-DENABLE_ZEEK_UNIT_TESTS=true \
-DZEEK_PYTHON_PREFIX=/usr
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export SOURCE_DATE_EPOCH=1666639564
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/zeek
cp %{_builddir}/zeek-%{version}/COPYING %{buildroot}/usr/share/package-licenses/zeek/9f2826a006f7a635589133fda8e09ee646aae24e || :
cp %{_builddir}/zeek-%{version}/COPYING.3rdparty %{buildroot}/usr/share/package-licenses/zeek/e321fe856142eac73512b559b2c823d2e8d8e832 || :
cp %{_builddir}/zeek-%{version}/auxil/bifcl/COPYING %{buildroot}/usr/share/package-licenses/zeek/095bff679080110031d9603cd5678de136085197 || :
cp %{_builddir}/zeek-%{version}/auxil/bifcl/cmake/COPYING %{buildroot}/usr/share/package-licenses/zeek/f2a190e0c1ddda28af4457907d2233f33d1f5fe5 || :
cp %{_builddir}/zeek-%{version}/auxil/binpac/COPYING %{buildroot}/usr/share/package-licenses/zeek/5e33d4674a821a666e7bb1fb7717d193ac234713 || :
cp %{_builddir}/zeek-%{version}/auxil/binpac/cmake/COPYING %{buildroot}/usr/share/package-licenses/zeek/f2a190e0c1ddda28af4457907d2233f33d1f5fe5 || :
cp %{_builddir}/zeek-%{version}/auxil/broker/COPYING %{buildroot}/usr/share/package-licenses/zeek/3ab1c7ffea3eb25703969e96f8f4a62ba6e36345 || :
cp %{_builddir}/zeek-%{version}/auxil/broker/bindings/python/3rdparty/pybind11/LICENSE %{buildroot}/usr/share/package-licenses/zeek/3dbd61e2b2c71dcc658c3da90bacf2e15958075a || :
cp %{_builddir}/zeek-%{version}/auxil/broker/caf-incubator/LICENSE %{buildroot}/usr/share/package-licenses/zeek/19ac7c04124b9f0a00b4e827a58cd368feba7b4a || :
cp %{_builddir}/zeek-%{version}/auxil/broker/caf/LICENSE %{buildroot}/usr/share/package-licenses/zeek/19ac7c04124b9f0a00b4e827a58cd368feba7b4a || :
cp %{_builddir}/zeek-%{version}/auxil/broker/cmake/COPYING %{buildroot}/usr/share/package-licenses/zeek/f2a190e0c1ddda28af4457907d2233f33d1f5fe5 || :
cp %{_builddir}/zeek-%{version}/auxil/broker/tests/benchmark/readerwriterqueue/LICENSE.md %{buildroot}/usr/share/package-licenses/zeek/e85bbc8175bc6b4a99301cd29a2f05118656b547 || :
cp %{_builddir}/zeek-%{version}/auxil/btest/COPYING %{buildroot}/usr/share/package-licenses/zeek/5e33d4674a821a666e7bb1fb7717d193ac234713 || :
cp %{_builddir}/zeek-%{version}/auxil/c-ares/LICENSE.md %{buildroot}/usr/share/package-licenses/zeek/e9c597f9b6cf935773ee731d4170b0c2ba142dbb || :
cp %{_builddir}/zeek-%{version}/auxil/gen-zam/COPYING %{buildroot}/usr/share/package-licenses/zeek/b471afe66ee4401fd4bdcb7a201255e80e122c72 || :
cp %{_builddir}/zeek-%{version}/auxil/gen-zam/cmake/COPYING %{buildroot}/usr/share/package-licenses/zeek/f2a190e0c1ddda28af4457907d2233f33d1f5fe5 || :
cp %{_builddir}/zeek-%{version}/auxil/highwayhash/LICENSE %{buildroot}/usr/share/package-licenses/zeek/5a7d7df655ba40478fae80a6abafc6afc36f9b6a || :
cp %{_builddir}/zeek-%{version}/auxil/libkqueue/LICENSE %{buildroot}/usr/share/package-licenses/zeek/0e0c1a21672c002945447e502e1fdce6c032dc12 || :
cp %{_builddir}/zeek-%{version}/auxil/libkqueue/pkg/debian/copyright %{buildroot}/usr/share/package-licenses/zeek/95b10a29e8110ff2823122f23729e173517a8a1e || :
cp %{_builddir}/zeek-%{version}/auxil/netcontrol-connectors/COPYING %{buildroot}/usr/share/package-licenses/zeek/7ba045683ca423eb9191e47cd13b80d9f8133d98 || :
cp %{_builddir}/zeek-%{version}/auxil/out_ptr/LICENSE %{buildroot}/usr/share/package-licenses/zeek/bbfec3dc6c195eae61bb0acb0c3e049a229341b0 || :
cp %{_builddir}/zeek-%{version}/auxil/package-manager/COPYING %{buildroot}/usr/share/package-licenses/zeek/1767b5180fbea2feaff4a90ecc7bd92effcf4458 || :
cp %{_builddir}/zeek-%{version}/auxil/package-manager/doc/ext/sphinxarg/LICENSE %{buildroot}/usr/share/package-licenses/zeek/67de873c1e71bb7719e25d2209dc44bdfc755db4 || :
cp %{_builddir}/zeek-%{version}/auxil/package-manager/testing/packages/rot13/COPYING.edit-me %{buildroot}/usr/share/package-licenses/zeek/133d0a39b5e2b6fe1640fdf72b961ba0fe78d348 || :
cp %{_builddir}/zeek-%{version}/auxil/paraglob/COPYING %{buildroot}/usr/share/package-licenses/zeek/6ebb0617457eb1bea6f5d6a8f29129a22f0ac1a1 || :
cp %{_builddir}/zeek-%{version}/auxil/rapidjson/bin/jsonschema/LICENSE %{buildroot}/usr/share/package-licenses/zeek/6808b97edf6d2c189571af702b95916168ff7db8 || :
cp %{_builddir}/zeek-%{version}/auxil/rapidjson/contrib/natvis/LICENSE %{buildroot}/usr/share/package-licenses/zeek/0c6ec50f76889bd113eacefe86f15b3dfcfb8e59 || :
cp %{_builddir}/zeek-%{version}/auxil/rapidjson/license.txt %{buildroot}/usr/share/package-licenses/zeek/47ab05791f28173ad2b82f25c2b5c7fc06252b4d || :
cp %{_builddir}/zeek-%{version}/auxil/rapidjson/thirdparty/gtest/LICENSE %{buildroot}/usr/share/package-licenses/zeek/5a2314153eadadc69258a9429104cd11804ea304 || :
cp %{_builddir}/zeek-%{version}/auxil/rapidjson/thirdparty/gtest/googlemock/LICENSE %{buildroot}/usr/share/package-licenses/zeek/5a2314153eadadc69258a9429104cd11804ea304 || :
cp %{_builddir}/zeek-%{version}/auxil/rapidjson/thirdparty/gtest/googlemock/scripts/generator/LICENSE %{buildroot}/usr/share/package-licenses/zeek/1d4719e04eaa4909ab5a59ef5cb04d2a5517716e || :
cp %{_builddir}/zeek-%{version}/auxil/rapidjson/thirdparty/gtest/googletest/LICENSE %{buildroot}/usr/share/package-licenses/zeek/5a2314153eadadc69258a9429104cd11804ea304 || :
cp %{_builddir}/zeek-%{version}/auxil/spicy-plugin/LICENSE %{buildroot}/usr/share/package-licenses/zeek/1b7fe0f0883efca8bce84c7c38473d61ff32f5b9 || :
cp %{_builddir}/zeek-%{version}/auxil/spicy/spicy/3rdparty/ArticleEnumClass-v2/LICENSE %{buildroot}/usr/share/package-licenses/zeek/d2057f161cc376853934a0258f672cb85f704120 || :
cp %{_builddir}/zeek-%{version}/auxil/spicy/spicy/3rdparty/LICENSE.3rdparty %{buildroot}/usr/share/package-licenses/zeek/0d64006ae04c72edc619d13f3954c63a01b1bf2a || :
cp %{_builddir}/zeek-%{version}/auxil/spicy/spicy/3rdparty/SafeInt/LICENSE %{buildroot}/usr/share/package-licenses/zeek/ca889c1e7f43a2306d28e5b479037f70ac544753 || :
cp %{_builddir}/zeek-%{version}/auxil/spicy/spicy/3rdparty/any/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/zeek/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/zeek-%{version}/auxil/spicy/spicy/3rdparty/benchmark/LICENSE %{buildroot}/usr/share/package-licenses/zeek/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/zeek-%{version}/auxil/spicy/spicy/3rdparty/doctest/LICENSE.txt %{buildroot}/usr/share/package-licenses/zeek/0894759b39fd4d199a2909db23855f861ac4b6fd || :
cp %{_builddir}/zeek-%{version}/auxil/spicy/spicy/3rdparty/fiber/LICENSE.md %{buildroot}/usr/share/package-licenses/zeek/bb716b1beccc5eed90344b63f121554f7184a9c0 || :
cp %{_builddir}/zeek-%{version}/auxil/spicy/spicy/3rdparty/fiber/cmake/cmake-utils/LICENSE.md %{buildroot}/usr/share/package-licenses/zeek/bb716b1beccc5eed90344b63f121554f7184a9c0 || :
cp %{_builddir}/zeek-%{version}/auxil/spicy/spicy/3rdparty/fiber/deps/cxx-header-utils/LICENSE.md %{buildroot}/usr/share/package-licenses/zeek/bb716b1beccc5eed90344b63f121554f7184a9c0 || :
cp %{_builddir}/zeek-%{version}/auxil/spicy/spicy/3rdparty/filesystem/LICENSE %{buildroot}/usr/share/package-licenses/zeek/fb35a530cb1bb57a2cfe303bf68bb6ce4a404fb0 || :
cp %{_builddir}/zeek-%{version}/auxil/spicy/spicy/3rdparty/json/LICENSE.MIT %{buildroot}/usr/share/package-licenses/zeek/5aa6321f397c4409e3f8f6e26481aab583dccdf8 || :
cp %{_builddir}/zeek-%{version}/auxil/spicy/spicy/3rdparty/pathfind/LICENSE %{buildroot}/usr/share/package-licenses/zeek/f45ee1c765646813b442ca58de72e20a64a7ddba || :
cp %{_builddir}/zeek-%{version}/auxil/spicy/spicy/3rdparty/reproc/LICENSE %{buildroot}/usr/share/package-licenses/zeek/7b04f5db0169eff3fa319fcc887aea1e903e6796 || :
cp %{_builddir}/zeek-%{version}/auxil/spicy/spicy/3rdparty/utf8proc/LICENSE.md %{buildroot}/usr/share/package-licenses/zeek/2e869637fb9ebe989de0188665cdd73c3cdb2b40 || :
cp %{_builddir}/zeek-%{version}/auxil/zeek-archiver/LICENSE %{buildroot}/usr/share/package-licenses/zeek/b413d9daa4f9c131505362b204d278b0cde8c661 || :
cp %{_builddir}/zeek-%{version}/auxil/zeek-aux/COPYING %{buildroot}/usr/share/package-licenses/zeek/5e33d4674a821a666e7bb1fb7717d193ac234713 || :
cp %{_builddir}/zeek-%{version}/auxil/zeek-aux/cmake/COPYING %{buildroot}/usr/share/package-licenses/zeek/f2a190e0c1ddda28af4457907d2233f33d1f5fe5 || :
cp %{_builddir}/zeek-%{version}/auxil/zeek-aux/plugin-support/skeleton/COPYING.edit-me %{buildroot}/usr/share/package-licenses/zeek/38a91fe77596c51b40b5192189c1de2a1396e127 || :
cp %{_builddir}/zeek-%{version}/auxil/zeek-client/LICENSE %{buildroot}/usr/share/package-licenses/zeek/e600b5317265eaee96efec3a5cdefa5cdcfa25c8 || :
cp %{_builddir}/zeek-%{version}/auxil/zeekctl/COPYING %{buildroot}/usr/share/package-licenses/zeek/5e33d4674a821a666e7bb1fb7717d193ac234713 || :
cp %{_builddir}/zeek-%{version}/auxil/zeekctl/auxil/capstats/COPYING %{buildroot}/usr/share/package-licenses/zeek/5e33d4674a821a666e7bb1fb7717d193ac234713 || :
cp %{_builddir}/zeek-%{version}/auxil/zeekctl/auxil/capstats/cmake/COPYING %{buildroot}/usr/share/package-licenses/zeek/f2a190e0c1ddda28af4457907d2233f33d1f5fe5 || :
cp %{_builddir}/zeek-%{version}/auxil/zeekctl/auxil/pysubnettree/COPYING %{buildroot}/usr/share/package-licenses/zeek/5e33d4674a821a666e7bb1fb7717d193ac234713 || :
cp %{_builddir}/zeek-%{version}/auxil/zeekctl/auxil/pysubnettree/cmake/COPYING %{buildroot}/usr/share/package-licenses/zeek/f2a190e0c1ddda28af4457907d2233f33d1f5fe5 || :
cp %{_builddir}/zeek-%{version}/auxil/zeekctl/auxil/trace-summary/COPYING %{buildroot}/usr/share/package-licenses/zeek/5e33d4674a821a666e7bb1fb7717d193ac234713 || :
cp %{_builddir}/zeek-%{version}/auxil/zeekctl/auxil/trace-summary/cmake/COPYING %{buildroot}/usr/share/package-licenses/zeek/f2a190e0c1ddda28af4457907d2233f33d1f5fe5 || :
cp %{_builddir}/zeek-%{version}/auxil/zeekctl/cmake/COPYING %{buildroot}/usr/share/package-licenses/zeek/f2a190e0c1ddda28af4457907d2233f33d1f5fe5 || :
cp %{_builddir}/zeek-%{version}/cmake/COPYING %{buildroot}/usr/share/package-licenses/zeek/f2a190e0c1ddda28af4457907d2233f33d1f5fe5 || :
cp %{_builddir}/zeek-%{version}/doc/LICENSE %{buildroot}/usr/share/package-licenses/zeek/3d1626ff5f531f387f20f25b36500bbe1f960e3d || :
pushd clr-build
%make_install
popd
## Remove excluded files
rm -f %{buildroot}*/var/spool/zeek/zeekctl-config.sh

%files
%defattr(-,root,root,-)
